### PR TITLE
Refactored the whole bot to Classes, cleanups and small fixes.

### PR DESCRIPTION
**Pull request by NoirPi**
finance_helper.py -> changed default_start and default_end to something more recent
helpers.py -> created a file for all helper functions which are used on different places in the code
commands.py -> File for all unsorted commands
greetings.py -> File for the greeting commands
greetings_cog.py -> removed
stocks.py -> File for the stock commands
tweets.py -> File for all tweet related commands
created a test folder which could contain all coming test files including unit tests.
removed bot_cmd.py and separated the functions into multiple files.
added main.py for basic bot features.
moved everything into classes to make it more clear and modular
changed requirements.txt so it will not use highly outdated libraries
updated ALL dependencies
Signed-off-by: NoirPi <NoirPi>

### CODE REVIEW

**Comment by hajderr** [comment]
Missing logs/ directory
```
Traceback (most recent call last):
  File "C:/Users/haider/GitProjects/discord-heaplevelbot/main.py", line 15, in <module>
    fh = logging.FileHandler(filename=f"./logs/bot_debug.log",
  File "C:\Users\haider\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\haider\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\haider\\GitProjects\\discord-heaplevelbot\\logs\\bot_debug.log'
```

discord Intents missing? did pip install -r requirements.txt also.

```
Traceback (most recent call last):
  File "C:/Users/haider/GitProjects/discord-heaplevelbot/main.py", line 70, in <module>
    Bot = Bot()
  File "C:/Users/haider/GitProjects/discord-heaplevelbot/main.py", line 34, in __init__
    intents=discord.Intents.default())
AttributeError: module 'discord' has no attribute 'Intents'
```

**Comment by NoirPi** [comment]
@hajderr which discord.py version you using?

For the first error create a folder logs in the root directory

**Comment by NoirPi** [comment]
I will add a function which checks for that folder and create it if not exist

**Comment by hajderr** [comment]
> @hajderr which discord.py version you using?
> 
> For the first error create a folder logs in the root directory

I use the same as in the requirements.txt in a venv. So it seems according to this it's a feature since 1.5 
https://discordpy.readthedocs.io/en/latest/intents.html

and the requirements.txt should reflect that. Can I update this PR too or how does it work?

```
(venv) C:\Users\haider\GitProjects\discord-heaplevelbot>pip freeze
aiohttp==3.6.3
async-timeout==3.0.1
attrs==20.3.0
certifi==2020.12.5
chardet==3.0.4
cycler==0.10.0
discord.py==1.3.4
idna==2.10
kiwisolver==1.3.1
lxml==4.6.2
matplotlib==3.3.3
multidict==4.7.6
multitasking==0.0.9
numpy==1.19.3
pandas==1.2.0
Pillow==8.1.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.4.1
requests==2.25.1
searchtweets==1.7.6
six==1.15.0
tweet-parser==1.13.2
urllib3==1.26.2
websockets==8.1
yarl==1.5.1
yfinance==0.1.54`

**Comment by NoirPi** [comment]
Edited requirements.txt to working lib versions.

Added Pathlib instruction to create logs folder if not exist.

**Review by hajderr — COMMENTED** [review]
Thanks for this

1. move remaining Twitter code like read_tweets to helpers.py. Right now bot_tests is error. 
2. Then it cannot seem to read this
```
premium_search_args = load_credentials(filename="../search_tweets_creds_example.yaml",
                                       yaml_key="search_tweets_ent_example",
                                       env_overwrite=False)```

```
cannot read file search_tweets_creds_example.yaml
Error parsing YAML file; searching for valid environment variables
Account type is not specified and cannot be inferred.
        Please check your credential file, arguments, or environment variables
        for issues. The account type must be 'premium' or 'enterprise'.
```

**Comment by NoirPi** [comment]
Actuall I feel a bit trolled xD

This credentials error occurred cause there are no credentials and no credentials file in this repo. Because of not having any idea how this file was builded in the original repo its on the repo owner to fix that.

**Comment by hajderr** [comment]
Haha that's ok, all good intentions here :)

Yes it's not committed because credentials should not be in the repo.

**Comment by NoirPi** [comment]
But an example for the structure of the file should be in the repo

**Comment by hajderr** [comment]
Right but still I'm new to this collaboration. If there are still changes should I push to your master before merging the PR?

**Comment by NoirPi** [comment]
Or you merge mine and change everything needed there cause actually there are no problems between your and my version detected. So changes can be made directly after merging

**Pull request merged**
